GET /api/customers/this-is-an-invalid-id
Host: localhost:8080
Accept: application/json

###
GET /api/customers/cc3247e4-1068-4dad-a250-26f0a8a8db36
Host: localhost:8080
Accept: application/json

###
GET /api/customers
Host: localhost:8080
Accept: application/json

###
GET /api/customers?city=Dashahe
Host: localhost:8080
Accept: application/json

###
GET /api/customers?_page=2
Host: localhost:8080
Accept: application/json

###
GET /api/customers?_limit=2
Host: localhost:8080
Accept: application/json

###
GET /api/customers?_limit=5&_page=3
Host: localhost:8080
Accept: application/json

###
GET /api/customers?_limit=asd&_page=asd
Host: localhost:8080
Accept: application/json

###
GET /api/customers?email=vinod12345@vinod.co
Host: localhost:8080
Accept: application/json

###
GET /api/customers?phone=9844083945
Host: localhost:8080
Accept: application/json

###
POST /api/customers
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
  "firstname": "Surya",
  "lastname": "Kayartaya",
  "gender": "Male",
  "email": "surya12340@vinod.co",
  "phone": "9844083940",
  "address": "1st crs, 1st main, ISRO lyt",
  "city": "Bangalore",
  "state": "Karnataka",
  "country": "India",
  "avatar": "https://avatars.githubusercontent.com/u/14976510?v=4"
}

###
PUT /api/customers/9e61dcdd-6e71-4ae4-baf8-2db3d84f8a0a
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
  "firstname": "Ramesh",
  "gender": "Kumar",
  "phone": "5204347062",
  "country": "India",
  "email": "tcron7@utexas.edu",
  "lastname": "Cron",
  "address": "13 Iowa Pass",
  "avatar": "https://robohash.org/utnullatemporibus.png?size=50x50&set=set1"
}

# city and state will be update as NULL in the DB (they are not part of the payload being sent)
# all other fields will be updated with above content
# id must be taken only from path variable (uri-segment)
# response should get the updated version of the resource, along with id
# respond with 404 if id is invalid

###
PATCH /api/customers/cc3247e4-1068-4dad-a250-26f0a8a8db36
Host: localhost:8080
Accept: application/json
Content-Type: application/json

{
  "city": "Chennai",
  "state": "Tamilnadu",
  "country": "India"
}

# Updates only the above fields, retaining all origin data in the database.
# response should get the updated data (with all fields in it)
# respond with 404 if id is invalid
# id is immutable; should not be changed!

###
DELETE /api/customers/9e61dcdd-6e71-4ae4-baf8-2db3d84f8a0a
Host: localhost:8080
Accept: application/json

###
